### ISSUE TITLE
Only `Application-Class` capsules are supported

### ISSUE THREAD

**Issue by trance1st** [puniverse/capsule-daemon#1]
When I am trying to run the following example 
https://github.com/puniverse/capsule-runnable-war
wrapping it with the capsule-daemon I am getting the following exception:

This is the command that I run:
java -jar capsule-daemon-0.1.0.jar target/capsule-runnable-war-maven.war

This is the exception:
CAPSULE: Using JVM: /usr/lib/jvm/java-8-oracle/jre
CAPSULE: Cleanup
CAPSULE EXCEPTION: -1 while processing attribute Application-Class: null
java.lang.ArrayIndexOutOfBoundsException: -1
    at java.util.ArrayList.elementData(ArrayList.java:418)
    at java.util.ArrayList.remove(ArrayList.java:495)
    at DaemonCapsule.setupUnixCmd(DaemonCapsule.java:534)
    at DaemonCapsule.toSvc(DaemonCapsule.java:197)
    at DaemonCapsule.prelaunch(DaemonCapsule.java:144)
    at Capsule.prelaunch(Capsule.java:1457)
    at Capsule.prepareForLaunch(Capsule.java:1311)
    at Capsule.launch(Capsule.java:1240)
    at Capsule.main0(Capsule.java:391)
    at Capsule.main(Capsule.java:370)

**Comment by circlespainter** [comment]
`0.2.0-SNAPSHOT` with a fix for this has been uploaded to Sonatype Snapshots.

**Comment by trance1st** [comment]
The issue is fixed starting with 0.2.0-SNAPSHOT. 

Thanks.
