### ISSUE TITLE
Fails to run under Capsule 1.0.1 under OS/X

### ISSUE THREAD

**Issue by talios** [puniverse/capsule-daemon#12]
I'm using capsule 1.0.1 and when I run my capsule on OSX I get the following:

```
CAPSULE: Launching app com.smxemail.appsuite.vacationservice-1.0.1-SNAPSHOT-capsule
CAPSULE: Copying daemon native helpers [jsvc/linux64-brew/jsvc, jsvc/macosx-yosemite-brew/jsvc, procrun/prunsrv.exe] in /Users/amrk/.capsule/apps/com.smxemail.appsuite.vacationservice-1.0.1-SNAPSHOT-capsule/bin
CAPSULE: Creating temp file/dir /Users/amrk/.capsule/apps/com.smxemail.appsuite.vacationservice-1.0.1-SNAPSHOT-capsule/bin
CAPSULE: Unlocking /Users/amrk/.capsule/apps/com.smxemail.appsuite.vacationservice-1.0.1-SNAPSHOT-capsule/.lock
CAPSULE: Cleanup
CAPSULE EXCEPTION: tried to access method Capsule.copy(Ljava/io/InputStream;Ljava/io/OutputStream;)V from class DaemonCapsule
java.lang.IllegalAccessError: tried to access method Capsule.copy(Ljava/io/InputStream;Ljava/io/OutputStream;)V from class DaemonCapsule
  at DaemonCapsule.copy(DaemonCapsule.java:183)
  at DaemonCapsule.setupBinDir(DaemonCapsule.java:171)
  at DaemonCapsule.getJavaExecutable(DaemonCapsule.java:116)
  at Capsule.getJavaExecutable(Capsule.java:2245)
  at Capsule.buildJavaProcess(Capsule.java:2203)
  at Capsule.buildProcess0(Capsule.java:1519)
  at Capsule.buildProcess(Capsule.java:1510)
  at Capsule.buildProcess(Capsule.java:1510)
  at Capsule.buildProcess(Capsule.java:1510)
  at Capsule.buildProcess(Capsule.java:1510)
  at Capsule.prelaunch0(Capsule.java:1483)
  at Capsule.prelaunch(Capsule.java:1476)
  at Capsule.prelaunch(Capsule.java:1476)
  at Capsule.prelaunch(Capsule.java:1476)
  at DaemonCapsule.prelaunch(DaemonCapsule.java:141)
  at Capsule.prelaunch(Capsule.java:1476)
  at Capsule.prepareForLaunch(Capsule.java:1329)
  at Capsule.launch(Capsule.java:1258)
  at Capsule.main0(Capsule.java:394)
  at Capsule.main(Capsule.java:374)
```

I'm using the `capsule-maven-plugin` with the following basic configuration:

```
  <plugin>
    <groupId>com.github.chrischristo</groupId>
    <artifactId>capsule-maven-plugin</artifactId>
    <version>1.1.1</version>
    <executions>
      <execution>
        <goals>
          <goal>build</goal>
        </goals>
        <configuration>
          <appClass>com.smxemail.appsuite.vacationservice.VacationMessageService</appClass>
          <caplets>co.paralleluniverse:capsule-daemon:0.1.0</caplets>
          <chmod>true</chmod>
          <types>fat</types>
        </configuration>
      </execution>
    </executions>
  </plugin>
```

**Comment by talios** [comment]
I just build `0.2.0-SNAPSHOT` locally from `HEAD@master` and the above problem no longer occurs, when after switching to using:

```
compile 'co.paralleluniverse:capsule:1.0'
```

in the `build.gradle` file.

Is there any chances of a new release?

**Comment by circlespainter** [comment]
It looks the same as #4. You don't need to build locally though, `0.2.0-SNAPSHOT` is published on SonaType. Can you try with the `capsule` `1.0.2-SNAPSHOT` and `capsule-daemon` `0.2.0-SNAPSHOT` both from SonaType?

As for the release, soon.
