### ISSUE TITLE
IllegalAccessError

### ISSUE THREAD

**Issue by chrisdchristo** [puniverse/capsule-daemon#4]
Trying to include capsule-daemon as a caplet.

Have a fat jar with the `capsule-daemon-0.1.0.jar` embedded at root. And then the manifest entry, `Caplets: co.paralleluniverse:capsule-daemon:0.1.0`.

But when executing I get the following error:

```
CAPSULE EXCEPTION: tried to access method Capsule.copy(Ljava/io/InputStream;Ljava/io/OutputStream;)V from class DaemonCapsule
java.lang.IllegalAccessError: tried to access method Capsule.copy(Ljava/io/InputStream;Ljava/io/OutputStream;)V from class DaemonCapsule
    at DaemonCapsule.copy(DaemonCapsule.java:183)
    at DaemonCapsule.setupBinDir(DaemonCapsule.java:171)
    at DaemonCapsule.getJavaExecutable(DaemonCapsule.java:116)
    at Capsule.getJavaExecutable(Capsule.java:2245)
    at Capsule.buildJavaProcess(Capsule.java:2203)
    at Capsule.buildProcess0(Capsule.java:1519)
    at Capsule.buildProcess(Capsule.java:1510)
    at Capsule.buildProcess(Capsule.java:1510)
    at Capsule.buildProcess(Capsule.java:1510)
    at Capsule.buildProcess(Capsule.java:1510)
    at Capsule.buildProcess(Capsule.java:1510)
    at Capsule.buildProcess(Capsule.java:1510)
    at Capsule.prelaunch0(Capsule.java:1483)
    at Capsule.prelaunch(Capsule.java:1476)
    at Capsule.prelaunch(Capsule.java:1476)
    at Capsule.prelaunch(Capsule.java:1476)
    at Capsule.prelaunch(Capsule.java:1476)
    at Capsule.prelaunch(Capsule.java:1476)
    at DaemonCapsule.prelaunch(DaemonCapsule.java:141)
    at Capsule.prelaunch(Capsule.java:1476)
    at Capsule.prepareForLaunch(Capsule.java:1329)
    at Capsule.launch(Capsule.java:1258)
    at Capsule.main0(Capsule.java:394)
    at Capsule.main(Capsule.java:374)
```

**Comment by circlespainter** [comment]
Does it still happen with `0.2.0-SNAPSHOT` (Sonatype)?

**Comment by circlespainter** [comment]
Yes it seems so.

**Comment by circlespainter** [comment]
New `0.2.0-SNAPSHOT` containing the fix published on SonaType.
